create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.tenses (
  id bigint primary key,
  name text not null unique,
  category text not null,
  icon text,
  description text,
  sort_order integer not null default 0
);

insert into public.tenses (id, name, category, icon, description, sort_order) values
  (1,'Simple Present','Present','🟢','Habits, routines and facts.',1),
  (2,'Present Continuous','Present','🔵','Actions happening now or around now.',2),
  (3,'Present Perfect','Present','🟣','Past actions connected to the present.',3),
  (4,'Present Perfect Continuous','Present','🟠','Actions continuing over a period of time.',4),
  (5,'Simple Past','Past','🟢','Completed actions in the past.',5),
  (6,'Past Continuous','Past','🔵','Actions in progress at a past time.',6),
  (7,'Past Perfect','Past','🟣','An earlier action before another past action.',7),
  (8,'Past Perfect Continuous','Past','🟠','An ongoing action before another past event.',8),
  (9,'Simple Future','Future','🚀','Predictions, promises and future actions.',9),
  (10,'Future Continuous','Future','⏳','An action that will be in progress.',10),
  (11,'Future Perfect','Future','🏆','An action completed before a future point.',11),
  (12,'Future Perfect Continuous','Future','⭐','Duration continuing up to a future point.',12)
on conflict (id) do update set
  name = excluded.name, category = excluded.category, icon = excluded.icon,
  description = excluded.description, sort_order = excluded.sort_order;

create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  tense_id bigint not null references public.tenses(id) on delete cascade,
  title text not null,
  content jsonb not null default '{}',
  sort_order integer not null default 0
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  tense_id bigint not null references public.tenses(id) on delete cascade,
  question_type text not null default 'mc',
  prompt text not null,
  options jsonb,
  correct_index integer,
  correct_text text,
  alternates text[],
  explanation text,
  difficulty smallint not null default 1 check (difficulty between 1 and 3),
  skill_type text,
  game_number smallint,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists questions_tense_idx on public.questions (tense_id) where is_active;

create table if not exists public.user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  tense_id bigint not null references public.tenses(id) on delete cascade,
  questions_attempted integer not null default 0,
  correct_answers integer not null default 0,
  mastery numeric(5,2) not null default 0,
  last_practiced timestamptz,
  next_review timestamptz,
  primary key (user_id, tense_id)
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete set null,
  tense_id bigint references public.tenses(id) on delete set null,
  selected_answer text,
  correct boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mistakes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete cascade,
  tense_id bigint references public.tenses(id) on delete cascade,
  prompt text,
  correct_answer text,
  explanation text,
  reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.achievements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null,
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_key)
);

create table if not exists public.streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  count integer not null default 0,
  last_date date
);

alter table public.profiles enable row level security;
alter table public.tenses enable row level security;
alter table public.lessons enable row level security;
alter table public.questions enable row level security;
alter table public.user_progress enable row level security;
alter table public.attempts enable row level security;
alter table public.mistakes enable row level security;
alter table public.achievements enable row level security;
alter table public.streaks enable row level security;

drop policy if exists "public read tenses" on public.tenses;
create policy "public read tenses" on public.tenses for select using (true);
drop policy if exists "public read lessons" on public.lessons;
create policy "public read lessons" on public.lessons for select using (true);
drop policy if exists "public read questions" on public.questions;
create policy "public read questions" on public.questions for select using (true);

drop policy if exists "own profile" on public.profiles;
create policy "own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "own progress" on public.user_progress;
create policy "own progress" on public.user_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own attempts" on public.attempts;
create policy "own attempts" on public.attempts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own mistakes" on public.mistakes;
create policy "own mistakes" on public.mistakes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own achievements" on public.achievements;
create policy "own achievements" on public.achievements for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own streaks" on public.streaks;
create policy "own streaks" on public.streaks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
